version: "3"

services:
  app:
    image: express-app
    container_name: app
    networks:
      - test-net
    expose:
      - "5000"

  test:
    image: express-app-test
    container_name: test
    networks:
      - test-net
    expose:
      - "5000"
    depends_on:
      - app

networks:
  test-net:
    name: test-net
    driver: bridge
