# Use the official Node.js image as the base image
FROM node:20-alpine

ENV ADDR="APP"

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install the dependencies
RUN npm install 

# Copy the rest of the application code
COPY . .

# Start the Express.js application
CMD ["npm", "test"]
