name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ vars.PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t express-app --build-arg PORT=${{ env.PORT || 8080 }} .

      - name: Run the express-app in a Docker container
        run: docker run -d -p ${{ env.PORT || 8080 }}:${{ env.PORT || 8080 }} express-app

      - name: Wait for the app to start
        run: npx wait-on http://localhost:${{ env.PORT || 8080 }}/api

      - name: Run Pactum tests inside the Docker container
        run: docker run --rm --network="host" -v $PWD:/usr/src/app -w /usr/src/app -e PORT=${{ env.PORT || 8080 }} express-app npm test

      - name: Stop and remove the running container
        run: docker stop $(docker ps -q --filter ancestor=express-app) || true
