name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ADDR: "app"
      PORT: ${{ vars.PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image for app
        run: docker build -t express-app --build-arg PORT=${{ env.PORT || 8080 }} .

      - name: Build the Docker image for test 
        run: docker build -t express-app-test --build-arg ADDR=${{ env.ADDR }} .

      - name: Run tests with docker compose
        run: docker-compose run test

