name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Start the Express app
        run: npm start &

      - name: Wait for the app to start
        run: npx wait-on http://localhost:${{ env.PORT || 8080 }}/api

      - name: Run Pactum tests
        run: npm test

      - name: Stop the Express app
        run: npx kill-port ${{ env.PORT || 8080 }}

